name: github-pages
on: push
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate GitHub Pages
      run: |
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        # Check out the `master` branch because by default GitHub Actions checks out detached HEAD
        git checkout master
        # Run the type check
        npm install
        npm run test
        npx tsc -p .
