name: github-pages
on: push
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the main branch
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Generate GitHub Pages
      run: |
        # Run the type check
        npm install
        npm run test
        npx tsc -p .
